import type { DiffResult } from '../types.js';

function markdownText(value: string): string {
  return value
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('|', '&#124;')
    .replaceAll('`', '&#96;')
    .replace(/\r\n?|\n/g, '<br>');
}

export function markdownReport(result: DiffResult): string {
  const lines = [
    '# SpecSentinel contract report', '',
    `**Baseline:** \`${markdownText(result.baseline)}\`  `,
    `**Candidate:** \`${markdownText(result.candidate)}\`  `,
    `**Findings:** ${result.summary.total}`, ''
  ];
  if (result.changes.length === 0) {
    lines.push('✅ No incompatible changes found.');
    return lines.join('\n');
  }
  lines.push('| Severity | Rule | Location | Change |', '| --- | --- | --- | --- |');
  for (const change of result.changes) {
    lines.push(`| **${change.severity.toUpperCase()}** | \`${markdownText(change.ruleId)}\` | \`${markdownText(change.location)}\` | ${markdownText(change.message)} |`);
  }
  lines.push('', '> Generated by SpecSentinel. Review intentional breaks and suppress only at the narrowest location.');
  return lines.join('\n');
}
